// Pins the per-type layout registry refactor (issue #44) as structural, NOT numerical.
// This pins the registry refactor as structural-not-numerical: if coordinates drift, the
// refactor changed math, not structure. The snapshot below is the exact x/y/w/h of every node
// in a representative multi-kind tree (group + grid + pool + icon + box, nested) computed by
// the OLD switch-based engine, frozen so any drift in the registry refactor fails here.
import { test } from "node:test";
import assert from "node:assert/strict";
import { icon, box, group, grid, pool, renderTree } from "../src/layout-engine.mjs";
import { Diagram } from "../src/builder.mjs";

function buildTree() {
  return group("root", null, "Region", { dir: "col", gap: 30 }, [
    group("svc", "group_region", "Services", { dir: "row", gap: 20 }, [
      icon("ic1", "s3", "Bucket"),
      box("b1", "Source\nendpoint"),
      grid("g1", null, "Cells", { cols: 2, gap: 16 }, [
        box("gc1", "A"), box("gc2", "BB"), box("gc3", "CCC"), box("gc4", "DDDD"),
      ]),
    ]),
    pool("p1", "Flow", { lanes: ["Lane0", "Lane1"], phases: ["Start", "End"] }, [
      { kind: "box", id: "n00", label: "T0", lane: 0, col: 0, w: 120, h: 44 },
      { kind: "box", id: "n01", label: "T1", lane: 0, col: 1, w: 120, h: 44 },
      { kind: "box", id: "n10", label: "T2", lane: 1, col: 0, w: 120, h: 44 },
      { kind: "box", id: "n11", label: "T3", lane: 1, col: 1, w: 120, h: 44 },
    ]),
  ]);
}

// Frozen snapshot of d.R (every node's x/y/w/h + ob) from the pre-refactor engine.
// Generated by rendering buildTree() and dumping JSON.stringify(d.R, null, 2).
const GOLDEN = {
  root: { x: 40, y: 70, w: 656, h: 594, ob: false },
  svc: { x: 64, y: 130, w: 608, h: 272, ob: false },
  ic1: { x: 112, y: 243, w: 48, h: 48, ob: true, labelH: 34 },
  b1: { x: 204, y: 253, w: 120, h: 62, ob: true },
  g1: { x: 344, y: 190, w: 304, h: 188, ob: false },
  gc1: { x: 368, y: 250, w: 120, h: 44, ob: true },
  gc2: { x: 504, y: 250, w: 120, h: 44, ob: true },
  gc3: { x: 368, y: 310, w: 120, h: 44, ob: true },
  gc4: { x: 504, y: 310, w: 120, h: 44, ob: true },
  p1: { x: 157, y: 432, w: 422, h: 208, ob: false },
  "p1__band0": { x: 283, y: 508, w: 280, h: 58 },
  "p1__lane0": { x: 173, y: 508, w: 110, h: 58 },
  "p1__band1": { x: 283, y: 566, w: 280, h: 58 },
  "p1__lane1": { x: 173, y: 566, w: 110, h: 58 },
  "p1__phase0": { x: 283, y: 466, w: 160, h: 26 },
  "p1__phase1": { x: 443, y: 466, w: 120, h: 26 },
  n00: { x: 283, y: 515, w: 120, h: 44, ob: true },
  n01: { x: 443, y: 515, w: 120, h: 44, ob: true },
  n10: { x: 283, y: 573, w: 120, h: 44, ob: true },
  n11: { x: 443, y: 573, w: 120, h: 44, ob: true },
};

test("registry refactor: golden coordinates unchanged across all 5 kinds", () => {
  const d = new Diagram();
  renderTree(d, buildTree(), [40, 70]);
  assert.deepEqual(d.R, GOLDEN);
});
