// drawio-ai-kit — core engine (zero-dependency, Node >=18, target Node 26)
// Provides: loadCatalog, searchIcon, styleForIcon, styleForGroup, validateDiagram.
// No external libraries so the CLI always runs, even when the MCP SDK is not installed.

import { existsSync, readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, isAbsolute, basename } from "node:path";
import { searchEntries } from "./search.ts";
import type {
  AuditResult, Catalog, CatalogEntry, EntryKind, GraphMetrics, LayoutSuggestion, Pack, RawEntry,
  SearchHit, SearchOptions, StyleResult, ValidationResult,
} from "./model.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
export const DEFAULT_CATALOG = join(__dirname, "..", "catalog", "aws.json");

const FAMILY = "mxgraph.aws4";

// Generated by `bun run build` (buildCatalogIndex): every sibling pack's entries minus embedded-image styles.
export const CATALOG_INDEX = join(__dirname, "..", "data", "catalog-index.json");
const isDataStyle = (s?: string) => /image=data:/.test(s ?? "");

// ponytail: parse each catalog once per process. bpmn.ts and every `new Diagram()` share it (read-only).
const CACHE = new Map<string, Catalog>();

/** Read the catalog JSON and build a lookup index (memoized per file). */
export function loadCatalog(path: string = DEFAULT_CATALOG): Catalog {
  const file = isAbsolute(path) ? path : join(process.cwd(), path);
  if (!CACHE.has(file)) CACHE.set(file, parseCatalog(file));
  return CACHE.get(file)!;
}

/** Sibling packs of the default catalog, with embedded-image styles replaced by `lazy: 1`. */
export function buildCatalogIndex(dir: string = dirname(DEFAULT_CATALOG)): Record<string, Pack> {
  const strip = (arr?: RawEntry[]): RawEntry[] => (arr ?? []).map(({ style, ...e }) => (isDataStyle(style) ? { ...e, lazy: 1 } : style == null ? e : { ...e, style }));
  const packs: Record<string, Pack> = {};
  for (const f of readdirSync(dir).sort()) {
    if (!f.endsWith(".json") || f === basename(DEFAULT_CATALOG)) continue;
    const p: Pack = JSON.parse(readFileSync(join(dir, f), "utf8"));
    packs[basename(f, ".json")] = { categoryColors: p.categoryColors ?? {}, icons: strip(p.icons), groups: strip(p.groups) };
  }
  return packs;
}

// Lazy packs: a pack's full JSON (~93% embedded images) is parsed only when one of its styles is read.
const PACK_STYLES = new Map<string, Map<string, string | undefined>>(); // "<dir>/<pack>" → Map("<kind>:<name>" → style)
function packStyle(dir: string, pack: string, kind: EntryKind, name: string): string | undefined {
  const key = join(dir, pack);
  if (!PACK_STYLES.has(key)) {
    const p: Pack = JSON.parse(readFileSync(`${key}.json`, "utf8"));
    PACK_STYLES.set(key, new Map([
      ...(p.icons ?? []).map((e): [string, string | undefined] => [`icon:${e.name}`, e.style]),
      ...(p.groups ?? []).map((e): [string, string | undefined] => [`group:${e.name}`, e.style]),
    ]));
  }
  return PACK_STYLES.get(key)!.get(`${kind}:${name}`);
}
/** Packs whose full JSON has been parsed so far (for tests). */
export const _loadedPacks = () => [...PACK_STYLES.keys()].map((k) => basename(k));
const withLazyStyle = (e: CatalogEntry, dir: string, kind: EntryKind): CatalogEntry =>
  e.lazy ? Object.defineProperty(e, "style", { get: () => packStyle(dir, e.pack, kind, e.name), enumerable: true }) : e;

function parseCatalog(file: string): Catalog {
  const raw: Pack & { meta?: Catalog["meta"] } = JSON.parse(readFileSync(file, "utf8"));
  const dir = dirname(file);
  // Each entry carries its pack name (catalog filename) so callers can filter per domain mode.
  const tag = (arr: RawEntry[], pack: string): CatalogEntry[] => arr.map((e) => ({ ...e, pack }));
  const basePack = basename(file, ".json");
  const icons = tag(raw.icons ?? [], basePack);
  const groups = tag(raw.groups ?? [], basePack);
  const categoryColors = { ...(raw.categoryColors ?? {}) };
  // Merge any sibling catalog/*.json icon packs (e.g. bigdata.json, databricks.json) so their
  // icons are searchable alongside AWS. Each pack contributes icons/groups/categoryColors.
  // The default catalog reads them from the slim index; a custom --catalog dir is parsed in full.
  let packs: Record<string, Pack> | null = null;
  try {
    packs = file === DEFAULT_CATALOG && existsSync(CATALOG_INDEX)
      ? JSON.parse(readFileSync(CATALOG_INDEX, "utf8"))
      : Object.fromEntries(readdirSync(dir).filter((f) => f.endsWith(".json") && join(dir, f) !== file)
          .map((f) => [basename(f, ".json"), JSON.parse(readFileSync(join(dir, f), "utf8"))]));
  } catch { /* no extra packs */ }
  for (const [packName, pack] of Object.entries(packs ?? {})) {
    if (Array.isArray(pack.icons)) icons.push(...tag(pack.icons, packName));
    if (Array.isArray(pack.groups)) groups.push(...tag(pack.groups, packName));
    // nosemgrep: insecure-object-assign -- merges the kit's own bundled catalog JSON, not user/request input
    Object.assign(categoryColors, pack.categoryColors ?? {});
  }
  // Spread before attaching getters, so building byName doesn't trigger a pack load.
  const byName = new Map<string, CatalogEntry>();
  for (const it of icons) byName.set(it.name, withLazyStyle({ ...it, kind: "icon" }, dir, "icon"));
  for (const g of groups) byName.set(g.name, withLazyStyle({ ...g, kind: "group" }, dir, "group"));
  for (const it of icons) withLazyStyle(it, dir, "icon");
  for (const g of groups) withLazyStyle(g, dir, "group");
  return { meta: raw.meta ?? {}, categoryColors, icons, groups, byName, validNames: new Set(byName.keys()) };
}

function norm(s: unknown): string {
  return String(s ?? "")
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

/** Search for an icon/group by keyword (minisearch: aliases, typo tolerance, vendor scope, multi-keyword). */
export function searchIcon(catalog: Catalog, query: string, { category, limit = 8, kind, full = false }: SearchOptions = {}): SearchHit[] {
  const cat = category ? norm(category) : null;
  return searchEntries(catalog, query, limit, (e) => {
    if (kind && e.kind !== kind) return false;
    return !cat || norm(e.category) === cat || norm(e.category).includes(cat);
  }).map((e) => decorate(catalog, e, undefined, { lean: true, compact: !full }));
}

function colorFor(catalog: Catalog, entry: CatalogEntry): string {
  return entry.color || catalog.categoryColors[entry.category ?? ""] || "#232F3E";
}

function decorate(catalog: Catalog, entry: CatalogEntry, score?: number, { lean = false, compact = false } = {}): SearchHit {
  // ponytail: compact = search-result shape. The agent builds with icon("<name>") and the engine
  // resolves the style server-side, so the ~600-char style string (plus fqn/aliases/score) is
  // pure context burn in search output. `drawio-ai style <name>` returns the full entry.
  if (compact) {
    return {
      name: entry.name,
      label: entry.label ?? entry.name,
      category: entry.category ?? null,
      kind: entry.kind,
      color: colorFor(catalog, entry),
    };
  }
  // byName lookups of an entry that came from byName always resolve, hence the `!`.
  const styleObj: StyleResult = lean && entry.lazy
    ? { style: "image=data:", width: entry.w ?? 48, height: entry.h ?? 48 }
    : entry.kind === "group" ? styleForGroup(catalog, entry.name) : styleForIcon(catalog, entry.name)!;
  // ponytail: pack icons embed a base64 SVG/PNG (up to 16KB) in the style. In search results (lean) don't
  // dump it into context — the model only needs the name; builder.icon(name) resolves the style
  // server-side, and get_icon_style(name) (not lean) returns it verbatim if raw XML is needed.
  const style = lean && /image=data:/.test(styleObj.style || "")
    ? `embedded-image; build with icon("${entry.name}") or fetch via get_icon_style`
    : styleObj.style;
  return {
    name: entry.name,
    fqn: `${FAMILY}.${entry.name}`,
    label: entry.label ?? entry.name,
    category: entry.category ?? null,
    kind: entry.kind,
    color: colorFor(catalog, entry),
    aliases: entry.aliases ?? [],
    style,
    ...(styleObj.width ? { width: styleObj.width, height: styleObj.height } : {}),
    ...(score != null ? { score } : {}),
  };
}

/** Full draw.io style for an AWS resource icon (verbatim from the index if available). */
export function styleForIcon(catalog: Catalog, name: string, { width, height }: { width?: number; height?: number } = {}): StyleResult | null {
  const entry = catalog.byName.get(name);
  if (!entry) return null;
  if (entry.style) return { style: entry.style, width: width ?? entry.w ?? 48, height: height ?? entry.h ?? 48 };
  // hand-built fallback (when the catalog is in the old seed form)
  const color = colorFor(catalog, entry);
  const style =
    `sketch=0;outlineConnect=0;fontColor=#232F3E;gradientColor=none;fillColor=${color};` +
    `strokeColor=none;dashed=0;verticalLabelPosition=bottom;verticalAlign=top;align=center;` +
    `html=1;fontSize=12;fontStyle=0;aspect=fixed;shape=${FAMILY}.resourceIcon;resIcon=${FAMILY}.${name};`;
  return { style, width: width ?? 48, height: height ?? 48 };
}

/** Style for a group container (AWS Cloud / Region / VPC / AZ ...) — verbatim from the index if available. */
export function styleForGroup(catalog: Catalog, name: string): StyleResult {
  const entry = catalog.byName.get(name);
  if (entry?.style) return { style: entry.style, width: entry.w, height: entry.h };
  const stroke = entry?.stroke || "#232F3E";
  const fill = entry?.fill || "none";
  const style =
    `sketch=0;outlineConnect=0;gradientColor=none;html=1;whiteSpace=wrap;fontSize=12;fontStyle=0;` +
    `container=1;pointerEvents=0;collapsible=0;recursiveResize=0;shape=${FAMILY}.group;` +
    `grIcon=${FAMILY}.${name};strokeColor=${stroke};fillColor=${fill};verticalAlign=top;align=left;` +
    `spacingLeft=30;fontColor=${stroke};dashed=${entry?.dashed ? 1 : 0};`;
  return { style };
}

const RE_RESICON = /resIcon=mxgraph\.aws4\.([a-z0-9_]+)/g;
const RE_GRICON = /grIcon=mxgraph\.aws4\.([a-z0-9_]+)/g;
const RE_SHAPE = /shape=mxgraph\.aws4\.([a-zA-Z0-9_]+)/g;
const RE_ID = /\bid="([^"]+)"/g;
const RE_SRC = /\bsource="([^"]+)"/g;
const RE_TGT = /\btarget="([^"]+)"/g;

function collect(re: RegExp, xml: string): string[] {
  const out: string[] = [];
  let m;
  re.lastIndex = 0;
  while ((m = re.exec(xml)) !== null) out.push(m[1]);
  return out;
}

/**
 * Validate a draw.io XML string:
 *  - whether every resIcon / grIcon exists in the catalog (guards against the AI inventing names)
 *  - whether edges reference existing ids
 *  - a few basic lint checks on icon styles
 * Returns { ok, errors, warnings, stats }.
 */
export function validateDiagram(catalog: Catalog, xml: string, { strict = false }: { strict?: boolean } = {}): ValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];
  const knownShapeWords = new Set(["resourceIcon", "resourceIcon2", "group", "groupCenter", "productIcon"]);

  // Guard: no <mxCell> at all means there is nothing to validate — most often a COMPRESSED .drawio
  // (draw.io desktop's default save format base64-deflates the <diagram> body). Without this guard
  // the file silently passes as "ok" with zero checks run.
  if (!/<mxCell[\s>]/.test(xml)) {
    const looksCompressed =
      /<diagram[^>]*>[^<\s][A-Za-z0-9+/=\s]{40,}<\/diagram>/.test(xml) || // whole file
      /^[A-Za-z0-9+/=\s]{40,}$/.test(xml.trim());                          // bare tab body (per-tab path)
    errors.push(
      looksCompressed
        ? "No cells found — this .drawio appears to be COMPRESSED (draw.io's default save). Re-export uncompressed: File → Properties → uncheck Compressed, or Extras → Edit Diagram to copy plain XML."
        : "No <mxCell> elements found — nothing to validate (empty or unrecognized file).",
    );
    return { ok: false, errors, warnings, audit: { advice: [] } };
  }

  const resIcons = collect(RE_RESICON, xml);
  const grIcons = collect(RE_GRICON, xml);
  const shapes = collect(RE_SHAPE, xml).filter((s) => !knownShapeWords.has(s));

  const checkRef = (name: string, where: string) => {
    if (catalog.validNames.has(name)) return;
    const msg = `Stencil not found in catalog: mxgraph.aws4.${name} (at ${where})`;
    const suggestions = searchIcon(catalog, name.replace(/_/g, " "), { limit: 3 }).map((s) => s.name);
    const full = suggestions.length ? `${msg} — suggestions: ${suggestions.join(", ")}` : msg;
    if (strict || !catalog.meta.incomplete) errors.push(full);
    else warnings.push(full + " (catalog is in seed form and may be incomplete — run the generator to verify)");
  };

  for (const n of resIcons) checkRef(n, "resIcon");
  for (const n of grIcons) checkRef(n, "grIcon");
  for (const n of shapes) checkRef(n, "shape");

  // duplicate id check
  const allIds = collect(RE_ID, xml);
  const ids = new Set(allIds);
  if (allIds.length !== ids.size) {
    const seen = new Set<string>();
    for (const id of allIds) {
      if (seen.has(id)) errors.push(`Duplicate cell id: "${id}" — draw.io silently drops one of the cells, causing missing icons or broken edges.`);
      seen.add(id);
    }
  }

  // edge references
  const dangling: string[] = [];
  for (const re of [RE_SRC, RE_TGT]) {
    for (const ref of collect(re, xml)) {
      if (!ids.has(ref)) dangling.push(ref);
    }
  }
  for (const d of [...new Set(dangling)]) {
    warnings.push(`Edge references a non-existent id: "${d}"`);
  }

  // lint: every style containing resourceIcon should have aspect=fixed
  const iconStyles = xml.match(/style="[^"]*mxgraph\.aws4\.resourceIcon[^"]*"/g) ?? [];
  for (const c of iconStyles) {
    if (!/aspect=fixed/.test(c)) {
      warnings.push("resourceIcon missing 'aspect=fixed' → icon may become distorted when resized.");
      break;
    }
  }

  const audit = auditAesthetics(xml);
  audit.advice.push(...auditAwsConventions(catalog, xml));
  audit.advice.push(...auditEdgeLabels(xml));
  audit.advice.push(...auditGeometry(xml));
  audit.advice.push(...auditEdges(xml));
  audit.advice.push(...auditBpmn(xml));
  audit.advice.push(...auditArchitecture(xml));

  return {
    ok: errors.length === 0,
    errors,
    warnings,
    audit,
    stats: {
      resIcons: resIcons.length,
      grIcons: grIcons.length,
      shapes: shapes.length,
      uniqueStencils: new Set([...resIcons, ...grIcons, ...shapes]).size,
      cellIds: ids.size,
    },
  };
}

const RE_OPENCELL = /<mxCell\b[^>]*?>/g;
function attr(tag: string, name: string): string | null {
  // nosemgrep: detect-non-literal-regexp -- `name` is an internal attribute name (fixed set), not external input; pattern is linear
  const m = tag.match(new RegExp(`\\b${name}="([^"]*)"`));
  return m ? m[1] : null;
}
/** Read a numeric style key (exitX=0.5 …) from a style string. */
// nosemgrep: detect-non-literal-regexp -- `k` is an internal style-key name (fixed set), not external input; pattern is linear
const num = (style: string, k: string): number | null => { const m = style.match(new RegExp(`(?:^|;)${k}=([\\d.]+)`)); return m ? +m[1] : null; };

/**
 * Aesthetics check derived from comparing the AI-drawn version against the human-corrected one.
 * Only considers edge routing / layout / visual consistency. Returns advisories (not hard errors).
 */
export function auditAesthetics(xml: string): AuditResult {
  const advice: string[] = [];

  // 1) Font sizes: limit to 3–4 VERTEX sizes (edge-label size is an engine
  //    constant, not a design choice — don't count it against the budget).
  const fontSizes: number[] = [];
  let bigCells = 0;
  for (const tag of xml.match(RE_OPENCELL) ?? []) {
    if (/\bedge="1"/.test(tag)) continue;
    const s = num(attr(tag, "style") || "", "fontSize");
    if (s == null) continue;
    fontSizes.push(s);
    if (s >= 16) bigCells++;
  }
  const uniqFonts = [...new Set(fontSizes)].sort((a, b) => a - b);
  if (uniqFonts.length > 4)
    advice.push(`Too many font sizes (${uniqFonts.length}): [${uniqFonts.join(", ")}] — limit to 3–4 sizes for consistency.`);
  // One hero title/band per page may be large; flag repeated oversizing or extremes.
  const big = uniqFonts.filter((s) => s >= 16);
  if (bigCells > 1 || big.some((s) => s > 20))
    advice.push(`Font sizes too large [${big.join(", ")}] on ${bigCells} cells — use ≤ 14 for labels; at most one hero title per page.`);

  // 2) Palette: only count BACKGROUND/BOX colors — ignore AWS icon/group colors (mandated by category).
  const fills: string[] = [];
  for (const tag of xml.match(RE_OPENCELL) ?? []) {
    const st = attr(tag, "style") || "";
    if (/mxgraph\.aws4\.(resourceIcon|group)/.test(st)) continue; // icon/group colors are canonical
    const fm = st.match(/fillColor=([^;"}]+)/);
    if (fm) fills.push(fm[1].trim().toLowerCase());
  }
  const uniqFills = [...new Set(fills.filter((c) => c && c !== "none" && c !== "default"))];
  if (uniqFills.length > 8)
    advice.push(`Palette too scattered (${uniqFills.length} background colors) — use a limited palette, reserve strong colors for accents/notes.`);
  if (uniqFills.length && !/light-dark\(/.test(xml))
    advice.push("Consider light-dark(...) color tokens for backgrounds/accents so the diagram looks good in both light & dark mode.");

  // 3) Edges: collect source/target/style of every edge.
  const edges: { source: string | null; target: string | null; style: string }[] = [];
  for (const tag of xml.match(RE_OPENCELL) ?? []) {
    if (attr(tag, "edge") !== "1") continue;
    edges.push({ source: attr(tag, "source"), target: attr(tag, "target"), style: attr(tag, "style") || "" });
  }
  const bySource = new Map<string, typeof edges>();
  for (const e of edges) {
    if (!e.source) continue;
    if (!bySource.has(e.source)) bySource.set(e.source, []);
    bySource.get(e.source)!.push(e);
  }
  // fan-out (1 source → ≥3 targets): should use sharp corners + pinned connection points so the parallel edges align.
  for (const [src, list] of bySource) {
    if (list.length < 3) continue;
    if (list.every((e) => /rounded=1/.test(e.style)))
      advice.push(`Fan-out branch from "${src}" (${list.length} edges) should use rounded=0 (sharp corners) instead of rounded.`);
    if (list.every((e) => !/(exitX|entryX)=/.test(e.style)))
      advice.push(`Pin connection points (exitX/exitY, entryX/entryY) for the fan-out branch from "${src}" so the parallel edges align.`);
  }

  // 4) Consistent icon sizes.
  const iconW = [
    ...xml.matchAll(/<mxCell\b[^>]*resourceIcon[^>]*>\s*<mxGeometry\b[^>]*\bwidth="([\d.]+)"/g),
  ].map((m) => Number(m[1]));
  const uniqW = [...new Set(iconW)];
  if (uniqW.length > 2)
    advice.push(`Inconsistent icon sizes [${uniqW.sort((a, b) => a - b).join(", ")}] — should use a single size (e.g. 48 or 78).`);

  return {
    advice,
    metrics: { fontSizes: uniqFonts, fillColors: uniqFills.length, edges: edges.length, fanOutSources: [...bySource.values()].filter((l) => l.length >= 3).length },
  };
}

// AWS group nesting hierarchy: lower number = outermost.
// "Top" containers (Cloud/Account/Region/DC) are all = 0 — they can nest under several conventions
// (Account>Region in Landing Zone style, or Region>Account in mesh style), so we don't enforce an
// order among them. We only enforce the network chain: VPC → AZ → Subnet → Security Group.
const GROUP_LEVEL: Record<string, number> = {
  group_aws_cloud: 0, group_aws_cloud_alt: 0, group_account: 0,
  group_corporate_data_center: 0, group_on_premise: 0, group_region: 0,
  group_vpc: 2, group_vpc2: 2,
  group_availability_zone: 3,
  group_subnet: 4,
  group_security_group: 5,
};

/**
 * Check conventions specific to AWS architecture:
 *  - icons recolored away from their standard category color (loss of recognizability).
 *  - groups nested in the wrong order (AWS Cloud→Region→VPC→AZ→Subnet→SG).
 * Returns advisories.
 */
export function auditAwsConventions(catalog: Catalog, xml: string): string[] {
  const advice: string[] = [];
  const cells = (xml.match(RE_OPENCELL) ?? []).map((tag) => ({
    id: attr(tag, "id"),
    parent: attr(tag, "parent"),
    edge: attr(tag, "edge"),
    style: attr(tag, "style") || "",
  }));
  const byId = new Map(cells.filter((c) => c.id).map((c) => [c.id, c] as const));

  // 1) Icon recolored relative to its own standard color.
  for (const c of cells) {
    const m = c.style.match(/resIcon=mxgraph\.aws4\.([a-zA-Z0-9_]+)/);
    if (!m) continue;
    const entry = catalog.byName.get(m[1]);
    if (!entry?.color) continue;
    const fm = c.style.match(/fillColor=([^;]+)/);
    if (!fm) continue;
    const used = fm[1].trim().toLowerCase();
    if (used.startsWith("light-dark")) continue;
    if (used !== String(entry.color).trim().toLowerCase())
      advice.push(`Icon "${m[1]}" has been recolored (fillColor=${fm[1].trim()} ≠ standard color ${entry.color}) — keep the category color for easy recognition.`);
  }

  // 2) Groups nested in the correct order.
  // A labelled subnet swaps its glyph to the security-group padlock but carries a `subnet=1` marker
  // (builder.group) — treat it as a subnet, not a security group, for nesting order.
  const groupTok = (style: string): string | undefined =>
    /(?:^|;)subnet=1;?/.test(style) ? "group_subnet" : (style.match(/grIcon=mxgraph\.aws4\.([a-zA-Z0-9_]+)/) || [])[1];
  const ancestorLevels = (c: (typeof cells)[number]) => {
    const out: number[] = [];
    let p = byId.get(c.parent);
    let guard = 0;
    while (p && guard++ < 50) {
      const g = groupTok(p.style);
      if (g != null && GROUP_LEVEL[g] != null) out.push(GROUP_LEVEL[g]);
      p = byId.get(p.parent);
    }
    return out;
  };
  const allLevels = cells.map((c) => GROUP_LEVEL[groupTok(c.style) ?? ""]).filter((l) => l != null);
  for (const c of cells) {
    const g = groupTok(c.style);
    if (g == null) continue;
    const lvl = GROUP_LEVEL[g];
    if (lvl == null || lvl === 0) continue; // top-level or unranked group
    // only warn if there IS a higher-level container in the diagram but this group is not inside it
    if (allLevels.some((l) => l < lvl) && !ancestorLevels(c).some((l) => l < lvl))
      advice.push(`Group "${g}" should be nested inside a higher-level group (AWS Cloud→Region→VPC→AZ→Subnet→SG) — currently placed flat / in the wrong order.`);
  }

  // 3) Rounded frames — AWS architecture diagrams use SQUARE corners for boxes/frames.
  //    (Skip edges: rounded on an edge smooths its corners, unrelated. Skip AWS stencils & text.)
  const roundedFrames = cells
    .filter((c) => c.edge !== "1" && /(?:^|;)rounded=1/.test(c.style) && !/mxgraph\.aws4\./.test(c.style) && !/(?:^|;)text;/.test(c.style))
    .map((c) => c.id || "?");
  if (roundedFrames.length)
    advice.push(`Rounded frame(s) found (${roundedFrames.length}: ${roundedFrames.slice(0, 6).join(", ")}${roundedFrames.length > 6 ? "…" : ""}) — AWS diagrams use SQUARE corners; set rounded=0 on these boxes/frames.`);

  return advice;
}

interface Box { x: number; y: number; w: number; h: number }
interface Pt { x: number; y: number }
/** One mxCell with geometry (relative to its parent) and, once resolved, absolute geometry. */
interface ParsedCell {
  id: string | null; parent: string | null; source: string | null; target: string | null;
  edge: string | null; value: string | null; style: string;
  hasPoints: boolean; wp: Pt[]; geo: Box | null; absGeo?: Box;
}

// ponytail: one-entry memo — validateDiagram runs 5 audits over the same xml; audits never mutate the cells.
let lastParsed: { xml: string; cells: ParsedCell[] } | undefined;
/** Parse every mxCell (with geometry & waypoint flag) for coordinate-based checks. */
function parseCells(xml: string): ParsedCell[] {
  if (lastParsed?.xml !== xml) lastParsed = { xml, cells: parseCellsUncached(xml) };
  return lastParsed.cells;
}
function parseCellsUncached(xml: string): ParsedCell[] {
  const out: ParsedCell[] = [];
  for (const ch of xml.split(/<mxCell\b/).slice(1)) {
    const end = ch.indexOf(">");
    const head = ch.slice(0, end + 1);
    const body = ch.slice(end + 1);
    // nosemgrep: detect-non-literal-regexp -- `n` is an internal attribute name (fixed set), not external input; pattern is linear
    const a = (n: string) => { const m = head.match(new RegExp(`\\b${n}="([^"]*)"`)); return m ? m[1] : null; };
    let geo: Box | null = null;
    const g = body.match(/<mxGeometry\b[^>]*?(?:\/>|>)/);
    if (g) {
      const t = g[0];
      const gx = t.match(/\bx="(-?[\d.]+)"/), gy = t.match(/\by="(-?[\d.]+)"/);
      const gw = t.match(/\bwidth="([\d.]+)"/), gh = t.match(/\bheight="([\d.]+)"/);
      if (gx && gy && gw && gh) geo = { x: +gx[1], y: +gy[1], w: +gw[1], h: +gh[1] };
    }
    const wp = [...body.matchAll(/<mxPoint\s+x="(-?[\d.]+)"\s+y="(-?[\d.]+)"\s*\/>/g)].map((m) => ({ x: +m[1], y: +m[2] }));
    out.push({ id: a("id"), parent: a("parent"), source: a("source"), target: a("target"), edge: a("edge"), value: a("value"), style: a("style") || "", hasPoints: /as="points"/.test(body), wp, geo });
  }
  // resolve ABSOLUTE coordinates for nested cells (geometry in the XML is relative to the parent)
  const byId = new Map(out.filter((c) => c.id).map((c) => [c.id, c] as const));
  for (const c of out) {
    if (!c.geo) continue;
    let ax = c.geo.x, ay = c.geo.y, p = byId.get(c.parent), guard = 0;
    while (p && p.geo && guard++ < 50) { ax += p.geo.x; ay += p.geo.y; p = byId.get(p.parent); }
    c.absGeo = { x: ax, y: ay, w: c.geo.w, h: c.geo.h };
  }
  return out;
}

/**
 * Edge labels on bent routes (L/Z): when source & target are offset in both X and Y but the edge
 * has no waypoint, the label (by default at the midpoint of the arc) tends to fall on the bend / box
 * edge → it looks misaligned.
 * Recommendation: add one waypoint in the middle of the corridor so the label sits centered on a straight segment.
 */
export function auditEdgeLabels(xml: string): string[] {
  const advice: string[] = [];
  const bentLabels: string[] = [];
  const cells = parseCells(xml);
  const geoOf = new Map<string | null, Box>();
  for (const c of cells) if (c.geo && c.id) geoOf.set(c.id, c.absGeo || c.geo);
  // absolute connection point: prefer pinned exit/entry, otherwise use the node center
  const point = (g: Box, fx: number | null, fy: number | null): Pt => ({ x: g.x + (fx != null ? fx : 0.5) * g.w, y: g.y + (fy != null ? fy : 0.5) * g.h });
  for (const c of cells) {
    if (c.edge !== "1") continue;
    const label = (c.value || "").trim();
    if (!label || c.hasPoints) continue;
    const sg = geoOf.get(c.source), tg = geoOf.get(c.target);
    if (!sg || !tg) continue;
    const ep = point(sg, num(c.style, "exitX"), num(c.style, "exitY"));
    const np = point(tg, num(c.style, "entryX"), num(c.style, "entryY"));
    const straight = Math.abs(ep.y - np.y) <= 8 || Math.abs(ep.x - np.x) <= 8; // horizontally or vertically straight
    if (!straight) bentLabels.push(`"${label}"`);
  }
  // ponytail: one aggregated line — the per-label sentence repeated N times cost ~170 B per finding
  // in every validate pass of every fix iteration
  if (bentLabels.length)
    advice.push(`Edge label(s) ${bentLabels.join(", ")} sit on a bent route (L/Z) — add one waypoint in the middle of each corridor so the label sits centered on a straight segment.`);
  return advice;
}

/**
 * Geometric audit — catches the visual bugs that name/color/nesting checks miss, WITHOUT a render:
 *  1. a child cell spilling outside its parent container ("box exceeds its frame"),
 *  2. two sibling leaf cells whose boxes PARTIALLY overlap (a real collision, not intentional layering),
 *  3. multiple edges entering one target at the same point (stacked arrowheads).
 * Works off absolute geometry resolved through the parent chain. Tuned to avoid false positives on
 * intentional layering (a badge icon fully inside a box, a bus spanning across a container).
 */
export function auditGeometry(xml: string): string[] {
  const advice: string[] = [];
  const cells = parseCells(xml);
  const byId = new Map(cells.filter((c) => c.id).map((c) => [c.id, c] as const));
  const hasChildren = new Set(cells.map((c) => c.parent).filter(Boolean));
  const TOL = 3;
  const box = (c: ParsedCell) => (c.absGeo || c.geo)!;
  const isText = (c: ParsedCell) => /(?:^|;)text;/.test(c.style) || c.id === "__title";
  const isContainer = (c: ParsedCell) => /container=1|shape=mxgraph\.aws4\.group|grIcon=/.test(c.style) || hasChildren.has(c.id);
  const isVertex = (c: ParsedCell) => c.edge !== "1" && c.geo && c.id && !isText(c);
  const contains = (a: Box, b: Box) => b.x >= a.x - TOL && b.y >= a.y - TOL && b.x + b.w <= a.x + a.w + TOL && b.y + b.h <= a.y + a.h + TOL;

  // 1) child spilling outside its parent container
  for (const c of cells) {
    if (!isVertex(c)) continue;
    const p = byId.get(c.parent);
    if (!p || !p.geo) continue;                 // parent must be a real container box (not root layer "1")
    const cb = box(c), pb = box(p);
    if (cb.x < pb.x - TOL || cb.y < pb.y - TOL || cb.x + cb.w > pb.x + pb.w + TOL || cb.y + cb.h > pb.y + pb.h + TOL)
      advice.push(`Cell "${c.id}" spills outside its container "${c.parent}" — enlarge the frame or shrink/reposition the child.`);
  }

  // 2) overlapping sibling LEAF cells (same parent, neither a container, partial overlap only)
  const sibsOf = new Map<string | null, ParsedCell[]>();
  for (const c of cells) {
    if (!isVertex(c) || isContainer(c)) continue;
    if (/__stk\d+$/.test(c.id!)) continue;   // multiplicity shadow cards overlap BY DESIGN (stack:N frames)
    (sibsOf.get(c.parent) ?? sibsOf.set(c.parent, []).get(c.parent)!).push(c);
  }
  const seen = new Set<string>();
  for (const [, sibs] of sibsOf) {
    for (let i = 0; i < sibs.length; i++) for (let j = i + 1; j < sibs.length; j++) {
      const a = box(sibs[i]), b = box(sibs[j]);
      const ix = Math.min(a.x + a.w, b.x + b.w) - Math.max(a.x, b.x);
      const iy = Math.min(a.y + a.h, b.y + b.h) - Math.max(a.y, b.y);
      if (ix <= TOL || iy <= TOL) continue;                       // not overlapping
      if (contains(a, b) || contains(b, a)) continue;             // intentional layering (badge in box)
      const minArea = Math.min(a.w * a.h, b.w * b.h);
      if (ix * iy < minArea * 0.2) continue;                      // ignore slight touches
      const key = [sibs[i].id!, sibs[j].id!].sort().join("|");
      if (seen.has(key)) continue; seen.add(key);
      advice.push(`Cells "${sibs[i].id}" and "${sibs[j].id}" overlap — space them apart (the layout engine keeps siblings from colliding).`);
    }
  }

  // 3) stacked arrowheads: ≥2 edges into the same target at the same entry point
  const entryCount = new Map<string, number>();
  for (const c of cells) {
    if (c.edge !== "1" || !c.target) continue;
    const ex = (c.style.match(/entryX=([\d.]+)/) ?? [, "c"])[1];
    const ey = (c.style.match(/entryY=([\d.]+)/) ?? [, "c"])[1];
    const k = `${c.target}@${ex},${ey}`;
    entryCount.set(k, (entryCount.get(k) ?? 0) + 1);
  }
  for (const [k, n] of entryCount) if (n > 1)
    advice.push(`${n} edges enter "${k.split("@")[0]}" at the same point — spread their entry points so the arrowheads don't stack (fan-in).`);

  // 4) ambiguous visual relay: an incoming edge and an outgoing edge attached to a node at the SAME
  //    explicit port read as the signal passing THROUGH the node (a relay), not stopping at it.
  //    (nexcanvas collision contract). Only flag explicit numeric ports — auto ports ("c") route apart.
  const port = (style: string, ax: string, ay: string) => {
    const x = (style.match(new RegExp(ax + "=([\\d.]+)")) ?? [])[1], y = (style.match(new RegExp(ay + "=([\\d.]+)")) ?? [])[1];
    return x != null && y != null ? `${x},${y}` : null;                // null = auto → not a shared-port risk
  };
  const inPorts = new Map<string, Set<string>>(), outPorts = new Map<string, Set<string>>();
  for (const c of cells) {
    if (c.edge !== "1") continue;
    const { source, target } = c;
    const ip = target && port(c.style, "entryX", "entryY"); if (ip) (inPorts.get(target) ?? inPorts.set(target, new Set()).get(target)!).add(ip);
    const op = source && port(c.style, "exitX", "exitY"); if (op) (outPorts.get(source) ?? outPorts.set(source, new Set()).get(source)!).add(op);
  }
  for (const [node, ins] of inPorts) {
    const outs = outPorts.get(node); if (!outs) continue;
    for (const p of ins) if (outs.has(p)) {
      advice.push(`Node "${node}" has an incoming and an outgoing edge at the same port (${p}) — it reads as a pass-through relay; give the outgoing edge a different side (exit/entry) so the flow clearly stops at the node.`);
      break;
    }
  }

  return advice;
}

const TOPOLOGY_GR = /group_(vpc|region|availability_zone|subnet|account|security_group|on_premise|corporate_data_center)|azure_.*(vnet|subnet|resource_group)|gcp_.*(vpc|subnet|project)/i;

/** Measure the graph a diagram declares (from its .drawio) into archetype-selection metrics.
 *  Inspired by nexcanvas' pre-geometry "layout brainstorm" — but computed from the built diagram so
 *  it plugs into the existing validate/audit loop. */
export function graphFromXml(xml: string): GraphMetrics {
  const cells = parseCells(xml);
  const byId = new Map(cells.filter((c) => c.id).map((c) => [c.id, c] as const));
  const hasChildren = new Set(cells.map((c) => c.parent).filter(Boolean));
  const box = (c: ParsedCell) => c.absGeo || c.geo;
  const isEdge = (c: ParsedCell) => c.edge === "1";
  const isText = (c: ParsedCell) => /(?:^|;)text;/.test(c.style) || c.id === "__title";
  // container = an AWS group stencil, an explicit container, or any cell that has children. Pack-agnostic
  // so GCP/Azure/Databricks label-frames (which carry no grIcon) still count as boundaries.
  const isGroup = (c: ParsedCell) => !isEdge(c) && (/grIcon=|container=1/.test(c.style) || hasChildren.has(c.id));
  // node = any leaf vertex (service icon OR box tile), across every pack — not a container, edge, or text.
  const isNode = (c: ParsedCell) => !isEdge(c) && c.geo && c.id && !isText(c) && !isGroup(c);
  const nodes = cells.filter(isNode);
  const groups = cells.filter(isGroup);
  const edges = cells.filter((c) => isEdge(c) && c.source && c.target);

  const depthOf = (c: ParsedCell, g = 0): number => { const p = byId.get(c.parent); return !p || g > 40 ? g : depthOf(p, g + 1); };
  const nestingDepth = groups.length ? Math.max(...groups.map((g) => depthOf(g))) : 0;
  const inGroup = (c: ParsedCell) => { let p = byId.get(c.parent); let n = 0; while (p && n++ < 40) { if (isGroup(p)) return true; p = byId.get(p.parent); } return false; };
  const containmentRatio = nodes.length ? nodes.filter(inGroup).length / nodes.length : 0;
  const TOPO_LABEL = /\b(vpc|subnet|region|zone|availability|project|vnet|resource group|account|namespace|cluster|data ?cent(er|re)|on[- ]?prem)\b/i;
  const topologyBoundary = groups.some((g) => TOPOLOGY_GR.test(g.style) || TOPO_LABEL.test(g.value || ""));

  const degree = new Map<string | null, number>();
  for (const e of edges) { degree.set(e.source, (degree.get(e.source) ?? 0) + 1); degree.set(e.target, (degree.get(e.target) ?? 0) + 1); }
  let hubId: string | null = null, maxDegree = 0;
  for (const [id, d] of degree) if (d > maxDegree) { maxDegree = d; hubId = id; }
  const hubScore = edges.length ? maxDegree / edges.length : 0;

  // back/feedback edges: a SOLID edge whose target sits left of (or above) the source. Dashed edges are
  // dependency/sync/governance, not feedback loops — exclude them.
  let backEdges = 0;
  for (const e of edges) { if (/(?:^|;)dashed=1/.test(e.style)) continue; const s = byId.get(e.source), t = byId.get(e.target); if (!s || !t) continue; const sb = box(s), tb = box(t); if (!sb || !tb) continue; if (tb.x + tb.w / 2 < sb.x - 8 || tb.y + tb.h / 2 < sb.y - 8) backEdges++; }

  // per-group icon packing — one-icon frames are the sparsity smell
  const directIcons = new Map<string | null, number>();
  for (const n of nodes) { const p = byId.get(n.parent); if (p && isGroup(p)) directIcons.set(n.parent, (directIcons.get(n.parent) ?? 0) + 1); }
  const maxIconsPerGroup = directIcons.size ? Math.max(...directIcons.values()) : nodes.length;
  const singleIconFrames = [...directIcons.values()].filter((v) => v === 1).length;

  const bx = nodes.concat(groups).map(box).filter((b): b is Box => b != null);
  const W = bx.length ? Math.max(...bx.map((b) => b.x + b.w)) - Math.min(...bx.map((b) => b.x)) : 1;
  const H = bx.length ? Math.max(...bx.map((b) => b.y + b.h)) - Math.min(...bx.map((b) => b.y)) : 1;

  // Wasted white space: the tallest EMPTY vertical band left inside any container (gap between the
  // children's bounding box and the frame edge). Vertical only — horizontal centring inside a wider frame
  // is normal, but a tall band above/below the content means the frame was stretched past what it holds.
  let emptyBand = 0, emptyBandId: string | null = null, emptyBandSide: "top" | "bottom" | null = null;
  for (const p of cells) {
    if (!p.geo || !isGroup(p)) continue;
    const kids = cells.filter((c) => c.parent === p.id && !isEdge(c) && c.geo && !isText(c) && !/__stk\d+$/.test(c.id!));
    if (!kids.length) continue;
    const pb = box(p);
    if (!pb || pb.h < 240) continue;                 // short frames: padding dominates, nothing to say
    const bs = kids.map(box).filter((b): b is Box => b != null);
    if (!bs.length) continue;
    const top = Math.min(...bs.map((b) => b.y)) - pb.y - 40;   // the top also carries the header strip
    const bottom = pb.y + pb.h - Math.max(...bs.map((b) => b.y + b.h));
    const [side, gap] = bottom >= top ? (["bottom", bottom] as const) : (["top", top] as const);
    if (gap > emptyBand) { emptyBand = gap; emptyBandId = p.id; emptyBandSide = side; }
  }

  return { nodeCount: nodes.length, edgeCount: edges.length, boundaryCount: groups.length, nestingDepth,
    containmentRatio: +containmentRatio.toFixed(2), topologyBoundary, maxDegree, hubId, hubScore: +hubScore.toFixed(2),
    backEdges, maxIconsPerGroup, singleIconFrames, emptyBand: Math.round(emptyBand), emptyBandId, emptyBandSide,
    portrait: H > W * 1.1, aspect: +(W / H).toFixed(2) };
}

/** Recommend a layout archetype from graph metrics (nexcanvas decision-flow thresholds), plus
 *  actionable warnings (sparsity, weak hub). Returns {recommended (our Diagram type), family, signals, warnings}. */
export function suggestLayout(m: GraphMetrics): LayoutSuggestion {
  const warnings: string[] = [];
  const feedbackRatio = m.edgeCount ? m.backEdges / m.edgeCount : 0;
  const signals = { hubScore: m.hubScore, containmentRatio: m.containmentRatio, topologyBoundary: m.topologyBoundary,
    feedbackRatio: +feedbackRatio.toFixed(2), nodeCount: m.nodeCount, maxIconsPerGroup: m.maxIconsPerGroup };

  // Only classify from signals that are reliable off a built diagram. Containment is NOT one — the kit
  // nests every icon in a layout wrapper, so it is high for all diagrams. Feedback/hybrid is surfaced as
  // a warning (back-edge geometry is noisy), not a reclassification.
  let family: string, type: string, reason: string;
  if (m.topologyBoundary) { family = "nested-topology"; type = "network"; reason = "topology boundaries (VPC/region/subnet/zone/account…)"; }
  else if (m.hubScore >= 0.45 && m.maxDegree >= 4) { family = "hub-and-spoke"; type = "hubspoke"; reason = `hub "${m.hubId}" carries ${Math.round(m.hubScore * 100)}% of edges (degree ${m.maxDegree})`; }
  else if (m.portrait) { family = "phase-rows"; type = "hierarchy"; reason = "portrait / top-to-bottom canvas"; }
  else if (m.nodeCount <= 10 && m.maxDegree <= 2) { family = "compact-pipeline"; type = "pipeline"; reason = `small linear story (${m.nodeCount} nodes, low branching)`; }
  else if (m.nodeCount >= 16 || m.maxIconsPerGroup >= 5) { family = "dense-phase-columns"; type = "pipeline"; reason = `large lifecycle (${m.nodeCount} nodes, up to ${m.maxIconsPerGroup}/group) → pack phases as GRIDS`; }
  else { family = "phase-columns"; type = "pipeline"; reason = "normal left-to-right lifecycle"; }

  // sparsity: one-icon-per-frame is the #1 quality failure — but only for a LARGE, UNPACKED diagram.
  // A small linear pipeline (a few stages, one service each) is fine; topology subnets carry 1 icon by
  // design. Fire only when there are many services, nothing is packed, and lone frames dominate.
  if (!m.topologyBoundary && m.nodeCount >= 12 && m.maxIconsPerGroup <= 2 && m.singleIconFrames >= 5)
    warnings.push(`${m.singleIconFrames} frames each hold a single icon while ${m.nodeCount} services stay unpacked — group related services into fewer grid() boxes (3–8 icons each) so the sheet reads dense, not scattered.`);
  if (m.emptyBand > 200)
    warnings.push(`"${m.emptyBandId}" leaves a ~${m.emptyBand}px empty band at the ${m.emptyBandSide} — it is far taller than what it holds (usually a short frame stretched to match a tall sibling). Pack more into it, split the tall sibling, or move a neighbouring box in, so the sheet has no dead white space.`);
  if (family !== "hub-and-spoke" && !m.topologyBoundary && m.hubScore >= 0.38 && m.hubScore < 0.45 && m.maxDegree >= 4) warnings.push(`node "${m.hubId}" is a near-hub (${Math.round(m.hubScore * 100)}% of edges) — hub-and-spoke may read better.`);
  if (!m.topologyBoundary && m.backEdges >= 2) warnings.push(`${m.backEdges} edges run backward — if they are feedback/sync draw them dashed; if the flow genuinely loops, a hybrid grid reads better.`);

  return { recommended: type, family, reason, signals, warnings };
}

// Databases are detected by name (the catalog "Database" category is noisy — it also tags cloud9,
// application_composer, cdk…). This list covers the data stores that must not sit in a public subnet.
const DB_NAME_RE = /^(rds|aurora|dynamodb|documentdb|docdb|redshift|elasticache|memorydb|neptune|timestream|database|memcached|opensearch|elasticsearch)/;

/**
 * Architecture / Well-Architected audit — semantic best-practice checks on the topology the diagram
 * already encodes (subnet placement, AZ count, gateways), NOT visual checks. Runs in the same
 * validate pass, so the advice lands in the same issues checklist the agent already loops on — it
 * catches design flaws at diagram time, before any IaC exists. AWS-only (gated on aws4 stencils).
 * Each advice cites the risk, the fix, and the pillar.
 *
 * ponytail: only rules that flag something PRESENT in the diagram (a DB literally in a public subnet,
 * a literally-singular NAT across AZs). Rules that infer from ABSENCE (e.g. "no gateway → missing
 * egress") fire on legitimate conceptual/simplified diagrams — a diagram-time tool can't read intent
 * — so they're left out; false positives erode trust in the advice faster than misses do.
 */
export function auditArchitecture(xml: string): string[] {
  const advice: string[] = [];
  if (!/mxgraph\.aws4\./.test(xml)) return advice;   // gate: only AWS diagrams
  const cells = parseCells(xml);
  const byId = new Map(cells.filter((c) => c.id).map((c) => [c.id, c] as const));
  const iconName = (c: ParsedCell) => (c.style.match(/resIcon=mxgraph\.aws4\.([a-z0-9_]+)/) ?? [])[1] ?? null;
  const isSubnet = (c: ParsedCell) => /(?:^|;)subnet=1;?/.test(c.style) || /grIcon=mxgraph\.aws4\.group_subnet\b/.test(c.style);
  const isAZ = (c: ParsedCell) => /grIcon=mxgraph\.aws4\.group_availability_zone\b/.test(c.style);
  const ancestors = (c: ParsedCell) => { const o: ParsedCell[] = []; let p = byId.get(c.parent), g = 0; while (p && g++ < 50) { o.push(p); p = byId.get(p.parent); } return o; };

  const icons = cells.map((c) => ({ c, name: iconName(c) })).filter((x) => x.name);
  const natCount = icons.filter((x) => /^nat_gateway/.test(x.name)).length;
  const azCount = cells.filter(isAZ).length;

  // Rule 1 — database in a PUBLIC subnet (Security)
  for (const { c, name } of icons) {
    if (!DB_NAME_RE.test(name)) continue;
    const sub = ancestors(c).find(isSubnet);
    if (sub && /public/i.test(sub.value || "")) {
      advice.push(`[well-arch] Database "${c.id}" (${name}) sits in a PUBLIC subnet ("${(sub.value || "").trim()}") — risk: the data store is directly reachable from the internet. Fix: move it to a private subnet and reach it via the app tier or a VPC endpoint. (Well-Architected: Security)`);
    }
  }

  // Rule 2 — single NAT gateway across multiple AZs (Reliability SPOF)
  if (azCount >= 2 && natCount === 1) {
    advice.push(`[well-arch] A single NAT gateway serves ${azCount} availability zones — risk: it is a single point of failure; if that AZ fails, every private subnet loses outbound internet. Fix: deploy one NAT gateway per AZ. (Well-Architected: Reliability)`);
  }

  return advice;
}

// Do two segments (p1-p2, p3-p4) properly cross? (orientation test, excludes shared endpoints)
function segsIntersect(p1: Pt, p2: Pt, p3: Pt, p4: Pt): boolean {
  const o = (a: Pt, b: Pt, c: Pt) => Math.sign((b.y - a.y) * (c.x - b.x) - (b.x - a.x) * (c.y - b.y));
  const o1 = o(p1, p2, p3), o2 = o(p1, p2, p4), o3 = o(p3, p4, p1), o4 = o(p3, p4, p2);
  return o1 !== o2 && o3 !== o4 && o1 !== 0 && o2 !== 0 && o3 !== 0 && o4 !== 0;
}

/**
 * Edge orchestration audit — catches the "ugly lines" the static checks miss, WITHOUT a render:
 *  1. very long connectors that span most of the diagram (a sign a node is parked far from its
 *     consumers — e.g. shared ECR/S3/CloudWatch dumped in a far row → long detour edges);
 *  2. an excessive number of edge crossings (the flow is tangled).
 * Both are PLACEMENT smells: the fix is to move nodes closer / group fan-out-fan-in, not to reroute.
 */
export function auditEdges(xml: string): string[] {
  const advice: string[] = [];
  const cells = parseCells(xml);
  const boxOf = (c: ParsedCell) => (c.absGeo || c.geo)!;
  const geoOf = new Map<string | null, Box>();
  for (const c of cells) if (c.edge !== "1" && (c.absGeo || c.geo) && c.id) geoOf.set(c.id, boxOf(c));
  if (geoOf.size === 0) return advice;
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  for (const g of geoOf.values()) { minX = Math.min(minX, g.x); minY = Math.min(minY, g.y); maxX = Math.max(maxX, g.x + g.w); maxY = Math.max(maxY, g.y + g.h); }
  const W = Math.max(1, maxX - minX), H = Math.max(1, maxY - minY);
  const center = (g: Box): Pt => ({ x: g.x + g.w / 2, y: g.y + g.h / 2 });

  const segs: { a: Pt; b: Pt; src: string; tgt: string; dashed: boolean }[] = [];
  for (const c of cells) {
    if (c.edge !== "1" || !c.source || !c.target) continue;
    const s = geoOf.get(c.source), t = geoOf.get(c.target);
    if (!s || !t) continue;
    segs.push({ a: center(s), b: center(t), src: c.source, tgt: c.target, dashed: /dashed=1/.test(c.style) });
  }
  if (segs.length === 0) return advice;

  // 1) long detour connectors: edges spanning most of the diagram. A few are normal (a DR link,
  //    a cross-account trust); but ≥3 is the signature of a node parked far from its consumers
  //    (e.g. shared ECR/S3/CloudWatch dumped in a far row) — every reference becomes a long line.
  // absolute floor: in a tiny diagram (a handful of nodes) EVERY edge spans "most of the diagram" —
  // proportional-only thresholds misfire there. Long means proportionally AND absolutely long.
  const longs = segs.filter((e) =>
    (Math.abs(e.a.y - e.b.y) > 0.45 * H && Math.abs(e.a.y - e.b.y) > 500) ||
    (Math.abs(e.a.x - e.b.x) > 0.55 * W && Math.abs(e.a.x - e.b.x) > 700));
  if (longs.length >= 3) {
    const names = longs.slice(0, 4).map((e) => `${e.src}→${e.tgt}`);
    advice.push(`Long connector(s) spanning most of the diagram (${longs.length}: ${names.join(", ")}${longs.length > 4 ? "…" : ""}) — place these nodes closer; keep shared resources (ECR/S3/CloudWatch/registries) in a band NEXT TO their consumers instead of a far-away row, to avoid long detour edges.`);
  }

  // 2) tangled flow (too many crossings)
  let crossings = 0;
  for (let i = 0; i < segs.length; i++) for (let j = i + 1; j < segs.length; j++) {
    const e = segs[i], f = segs[j];
    if (e.src === f.src || e.src === f.tgt || e.tgt === f.src || e.tgt === f.tgt) continue; // share an endpoint
    if (segsIntersect(e.a, e.b, f.a, f.b)) crossings++;
  }
  if (crossings > Math.max(4, Math.round(segs.length * 0.3)))
    advice.push(`${crossings} edge crossings — the flow looks tangled. Align the main flow on one row (spine), group fan-out/fan-in through a shared lane, and place shared nodes near their consumers.`);

  // 3) clearance: an edge's ACTUAL routed path (exit → waypoints → entry) must not run through a
  //    node it isn't connected to. Walls/containers (nodes holding an endpoint) are skipped.
  const onEdge = (g: Box, fx: number | null, fy: number | null): Pt => ({ x: g.x + (fx ?? 0.5) * g.w, y: g.y + (fy ?? 0.5) * g.h });
  const holds = (p: Box, q: Box) => q.x >= p.x - 2 && q.y >= p.y - 2 && q.x + q.w <= p.x + p.w + 2 && q.y + q.h <= p.y + p.h + 2;
  const segHitsRect = (a: Pt, b: Pt, r: Box) => {                // segment passes through the node's CORE (not grazing its edge)
    const ix = Math.min(r.w, r.h) * 0.3;
    return Math.max(a.x, b.x) > r.x + ix && Math.min(a.x, b.x) < r.x + r.w - ix &&
           Math.max(a.y, b.y) > r.y + ix && Math.min(a.y, b.y) < r.y + r.h - ix;
  };
  const hasChildren = new Set(cells.map((c) => c.parent).filter(Boolean));
  const isContainer = (c: ParsedCell) => hasChildren.has(c.id) || /container=1|shape=mxgraph\.aws4\.group|grIcon=/.test(c.style) || /fillColor=none/.test(c.style);
  const vts = cells
    .filter((c) => c.edge !== "1" && c.id && (c.absGeo || c.geo) && !isContainer(c) && !/(?:^|;)text;/.test(c.style))
    .map((c) => ({ id: c.id, r: boxOf(c) }))
    .filter((v) => v.r.w > 2 && v.r.h > 2);
  const hit = new Set();
  for (const c of cells) {
    if (c.edge !== "1" || !c.source || !c.target) continue;
    const sg = geoOf.get(c.source), tg = geoOf.get(c.target);
    if (!sg || !tg) continue;
    const poly = [onEdge(sg, num(c.style, "exitX"), num(c.style, "exitY")), ...(c.wp || []), onEdge(tg, num(c.style, "entryX"), num(c.style, "entryY"))];
    for (const v of vts) {
      if (v.id === c.source || v.id === c.target) continue;
      if (holds(v.r, sg) || holds(v.r, tg)) continue;   // a container of an endpoint
      for (let i = 0; i < poly.length - 1; i++) {
        if (segHitsRect(poly[i], poly[i + 1], v.r)) { hit.add(`${c.source}→${c.target} ⟂ ${v.id}`); break; }
      }
    }
  }
  if (hit.size)
    advice.push(`Edge(s) run THROUGH a node they don't connect to (${[...hit].slice(0, 4).join(", ")}${hit.size > 4 ? "…" : ""}) — reroute so the connector bends around the node instead of passing through it.`);

  // 4) floating arrowheads: edges anchored to a transparent leaf (not a real container)
  // hasChildren guards out AWS Cloud/Region/AZ/VPC group frames — those use fillColor=none legitimately.
  const isEmptyLeaf = (x: ParsedCell) => {
    if (x.edge === "1" || hasChildren.has(x.id)) return false;
    // clusterBox boundary frames (kit puts them on the "boundaries" layer) are LEGITIMATE edge
    // anchors — the rules explicitly say to link the cluster, not each replica inside it.
    if (x.parent === "boundaries") return false;
    const style = x.style || "";
    if (/(?:^|;)text;/.test(style) || x.id === "__title") return false;
    return /fillColor=none/.test(style) && !/grIcon=/.test(style);
  };
  const emptyLeaves = new Set(cells.filter(isEmptyLeaf).map((x) => x.id));
  const floaters: string[] = [];
  for (const c of cells) {
    if (c.edge !== "1") continue;
    if (c.target && emptyLeaves.has(c.target)) floaters.push(`${c.source}→${c.target}`);
    if (c.source && emptyLeaves.has(c.source)) floaters.push(`${c.source}→${c.target} (source)`);
  }
  if (floaters.length) {
    advice.push(`Edge(s) connect to an invisible leaf node (${[...new Set(floaters)].slice(0, 4).join(", ")}${floaters.length > 4 ? "…" : ""}) — anchor to a solid icon card instead of a transparent placeholder.`);
  }

  return advice;
}
/** BPMN semantic checks (gated: only runs when mxgraph.bpmn shapes are present).
 *  - gateway must split (≥2 outgoing) or merge (≥2 incoming) sequence flow
 *  - start event has no incoming; end event has no outgoing
 *  - no orphan flow object (a node connected to no sequence flow)
 *  ponytail: shape-name whitelist dropped — bpmn.ts creators throw at build time on unknown names
 *  (engine path can't emit an invalid stencil), and draw.io's BPMN stencil vastly exceeds our Tier-1
 *  set so strict whitelisting would false-flag legitimate shapes. Cross-pool sequence-flow check
 *  deferred (needs pool-membership resolution from coordinates; single-pool is the Tier-1 norm). */
export function auditBpmn(xml: string): string[] {
  const cells = parseCells(xml);
  const shape = (style: string) => (style.match(/shape=mxgraph\.bpmn\.([^;]+)/) || [])[1] || "";
  const flow = cells.filter((c) => c.style && /shape=mxgraph\.bpmn\./.test(c.style));
  if (flow.length === 0) return [];              // not a BPMN diagram
  const outDeg = new Map<string, number>(), inDeg = new Map<string, number>();
  for (const c of cells) {
    if (c.edge !== "1" || !c.source || !c.target) continue;
    outDeg.set(c.source, (outDeg.get(c.source) || 0) + 1);
    inDeg.set(c.target, (inDeg.get(c.target) || 0) + 1);
  }
  const deg = (id: string | null, m: Map<string, number>) => m.get(id!) || 0;
  const advice: string[] = [];
  for (const c of flow) {
    const sh = shape(c.style), outl = (c.style.match(/outline=([^;]+)/) || [])[1] || "", out = deg(c.id, outDeg), ins = deg(c.id, inDeg);
    const isGateway = /^gateway/.test(sh);
    const isStart = /^event/.test(sh) && outl === "standard";   // parametric: outline=standard → start event
    const isEnd = /^event/.test(sh) && outl === "end";           // parametric: outline=end → end event
    if (isGateway && out < 2 && ins < 2)
      advice.push(`BPMN gateway "${c.id}" neither splits (≥2 outgoing) nor merges (≥2 incoming) — a gateway should branch or join paths.`);
    if (isStart && ins > 0)
      advice.push(`BPMN start event "${c.id}" has an incoming sequence flow — a start event initiates the flow and should have no incoming edges.`);
    if (isEnd && out > 0)
      advice.push(`BPMN end event "${c.id}" has an outgoing sequence flow — an end event terminates the flow and should have no outgoing edges.`);
    if (out === 0 && ins === 0)
      advice.push(`BPMN flow object "${c.id}" (${sh}) is not connected to any sequence flow — orphan node.`);
  }
  return advice;
}

export function listCategories(catalog: Catalog, { excludePacks }: { excludePacks?: Set<string> } = {}): { category: string; count: number }[] {
  const counts = new Map<string, number>();
  for (const e of catalog.byName.values()) {
    if (excludePacks?.has(e.pack)) continue;
    const c = e.category ?? "(none)";
    counts.set(c, (counts.get(c) ?? 0) + 1);
  }
  return [...counts.entries()].sort((a, b) => a[0].localeCompare(b[0])).map(([category, count]) => ({ category, count }));
}

export function getIcon(catalog: Catalog, name: string): SearchHit | null {
  const e = catalog.byName.get(name);
  return e ? decorate(catalog, e) : null;
}
